### ISSUE TITLE
Missing variable value in email

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/admin-dashboard#19]
Submitted by member:

I replicated our new credentials email template and it "almost" worked correctly.
In this email, we use an issuer's name variable (for high school, undergraduate, etc) and we had a weird behavior. It shows an error when we load the CSV file because the credential is not using that variable name (yet) but shows no error when we load the email template (where we use that variable name). The email is sent but the value of that variable does not show up in the email.
On the other hand, if the CSV file does not have a column with the name of the organization but the email template requires it, the platform does not allow us to continue.

<img width="596" alt="missing org name 2024-02-02 at 4 26 30 p m" src="https://github.com/digitalcredentials/admin-dashboard/assets/206059/c1026bb2-882a-446c-942e-236dc4f70316">

**Comment by jchartrand** [comment]
@kayaelle I was able to reproduce the problem (or what I think was is problem) by using a variable name with a '.' in it. I think the problem is that handlebars interprets that as object syntax and goes looking for a 'name' property on an organization object. But the CSV column headings likely doesn't get parsed into an object-like structure.

So, the solution is likely to not use a '.' in the column titles.  In this case then it could instead be 'organizationName'
